spring:
  profiles: test
  datasource:
    url:  jdbc:h2:~/yogy
    driver-class-name: org.h2.Driver
    username: sa
    initialization-mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

  sql:
    init:
      platform: test
      schema-locations: classpath:schema.sql
      mode: always
      data-locations: classpath:data.sql

mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.example.demo.model

jwt:
  token:
    header: Authorization
    issuer: issuer
    secret: secret
    expirySeconds : 10000000

