
server:
  error:
    whitelabel:
      enabled: false
mybatis:
  mapper-locations: /mapper/**/*.xml
  type-aliases-package: com.example.demo.model

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
#    url: "jdbc:h2:mem:yogy;MODE=MYSQL;DB_CLOSE_DELAY=-1"
#    username: sa
#    password:
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 5
#      pool-name: H2_DB

  sql:
    init:
      platform: test
      schema-locations: classpath:schema.sql
      mode: always
      data-locations: classpath:data.sql


jwt:
  token:
    header: Authorization
    issuer: issuer
    secret: secret
    expirySeconds : 10000000

